berita/urls.py
from django.urls import path
from . import views
from .views import showBeritaViews


app_name = 'berita'

urlpatterns = [
    path('', showBeritaViews.as_view(), name='beritahome'),
]

bintang/urls.py
from django.urls import path
from django.conf.urls import url 

from . import views

app_name = 'bintang'

urlpatterns = [
    path('submisi/', views.submisi, name='submisi'),
    path('detail/<int:detail_id>', views.detail, name='detail'),
    path('delete/<int:delete_id>', views.delete, name='delete'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

projectsaveus/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('stats/', include('stats.urls')),
    path('bintang/', include('bintang.urls')),
    path('detil/', include('detil.urls')),
    path('berita/', include('berita.urls')),
    path('tips/', include('tips.urls')),
]

bintang/models.py
from django.db import models
from home.models import ShowSubmisi
# Create your models here.

class Cerita(models.Model):
    nama_pencerita = models.CharField(max_length = 50)
    email_pencerita = models.EmailField(max_length = 50)
    judul_pencerita = models.CharField(max_length = 50, null=True)
    cerita_pencerita = models.TextField(blank=False, null=False)
    published = models.DateTimeField(auto_now_add= True)
    # Hubungkan cerita dengan submisi pada app 'home'
    submisi = models.ForeignKey(ShowSubmisi, on_delete=models.CASCADE, null=True)

    def __stf__(self):
        return "{}. {}".format(self.id, self.nama_pencerita)

home/models.py
from django.db import models

class ShowSubmisi(models.Model):
    pass
            


# temporary model
# class Cerita(models.Model):
#     nama_pencerita = models.CharField(max_length=50)
#     email_pencerita = models.EmailField(max_length=50)
#     judul_pencerita = models.CharField(max_length=50, null=True)
#     cerita_pencerita = models.TextField(blank=False, null=False)
#     published = models.DateTimeField(auto_now_add=True)
#     submisi = models.ForeignKey(ShowSubmisi, on_delete=models.CASCADE)

#     def __str__(self):
#         return f"{self.id}. {self.nama_pencerita}"

#     def save(self, *args, **kwargs):
#         count = 1
#         if self.submisi.cerita_set.filter(email_pencerita=self.email_pencerita).exists():
#             self.id = self.submisi.cerita_set.count()
#         else :
#             self.id = self.submisi.cerita_set.count()+1
#         for i in self.submisi.cerita_set.all():
#             self.submisi.cerita_set.filter(id=i.id).update(id=count)
#             count += 1
#         super(Cerita, self).save(*args, **kwargs)

home/views.py
from django.shortcuts import render
from .models import ShowSubmisi
# Create your views here.

def index(request):
    if ShowSubmisi.objects.all().count() == 0:
        submisi = ShowSubmisi.objects.create(id=1)
    else:
        count = ShowSubmisi.objects.count()
        for i in range(1,count):
            ShowSubmisi.objects.all()[i].delete()
        submisi = ShowSubmisi.objects.all()[0]
        ShowSubmisi.objects.filter(id=submisi.id).update(id=1)
    return render(request, 'home/index.html', {'submisi':submisi})

home/templates/home/index.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
<title>Homepage</title>
<link rel="stylesheet" href="{% static 'css/home.css' %}">
<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.css">
<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
{% endblock meta %}

{% block content %}


<!-- Slider main container -->
<div class="swiper-container">
    <!-- Additional required wrapper -->
    <div class="swiper-wrapper">
        <!-- Slides -->
        <div class="swiper-slide">
            <img src="{% static 'img/Banner1_covid.svg' %}" alt="">
        </div>
        <div class="swiper-slide">Slide 2</div>
        <div class="swiper-slide">Slide 3</div>
        ...
    </div>
    <!-- If we need pagination -->
    <div class="swiper-pagination"></div>

    <!-- If we need navigation buttons -->
    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>

    <!-- If we need scrollbar -->
    <div class="swiper-scrollbar"></div>
</div>

<div class="middle">
    <div class="peta">
        <div class="peta-img">
            <img src="{% static 'img/peta1.png' %}" alt="">
        </div>
        <div class="peta-text">
            <h1>Persebaran</h1>
            <h1 style="color: rgb(238, 22, 22);">Covid-19</h1>
            <h1>Di</h1>
            <h1>Daerah</h1>
            <h1>Ibu Kota</h1>

            <a href="{% url 'berita:beritahome' %}" class="btn btn-info info-sel">INFO SELENGKAPNYA</a>
        </div>
    </div>
</div>

<div class="subm">
    <div class="submisi-title">
        <h2>Cerita Untuk Kamu</h2>
    </div>

    <div class="content">
        <div class="swiper-submisi">
            <div class="swiper-submisi-wrapper">
                {% if submisi.cerita_set.count != 0 %}
                {% for cerita in submisi.cerita_set.all %}
                <div class="card bg-light mb-3 submisi-card swiper-submisi-slide" style="width: 350px;">
                    <div class="card-header">Submisi #{{ forloop.counter }}</div>
                    <div class="card-body">
                        <h5 class="card-title">{{ cerita.judul_pencerita }}</h5>
                        <h6 class="card-subtitle">oleh {{ cerita.nama_pencerita }}</h6>
                    </div>
                    <a class="btn btn-primary" href="{% url 'bintang:detail' cerita.id %}"
                        style="color: aliceblue;">Baca Selengkapnya</a><br>
                    <a class="btn btn-danger" href="{% url 'bintang:delete' cerita.id %}" title="">Hapus Cerita Ini</a>
                    <div class="card-footer">
                        <p class="card-text">
                            {{ cerita.published }}
                        </p>
                    </div>
                </div>
                {% endfor %}
                {% endif %}
            </div>
            <div class="swiper-submisi-pagination"></div>
            <div class="swiper-submisi-scrollbar"></div>
        </div>
    </div>
</div>

<div class="to-submisi">
    <h1>Ayo ceritakan kisah atau tips-mu dalam menghadapi pandemi ini!</h1>
    <a href="{% url 'bintang:submisi' %}" class="btn btn-to-submisi">KLIK DISINI</a>
</div>


<script src="https://unpkg.com/swiper/swiper-bundle.js"></script>
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
<script src="{% static 'js/home.js' %}"></script>
{% endblock content %}