detil/urls.py
from django.urls import path
from . import views

app_name = 'detil'

urlpatterns = [
    path('<int:pk>', views.detil, name='detil'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

projectsaveus/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('stats/', include('stats.urls')),
    path('bintang/', include('bintang.urls')),
    path('detil/', include('detil.urls')),
    path('berita/', include('berita.urls')),
    path('tips/', include('tips.urls')),
]

stats/urls.py
from django.urls import path
from . import views
from .views import showprovinsiView


app_name = 'stats'

urlpatterns = [
    path('', showprovinsiView.as_view(), name='stathome'),
]

stats/models.py
from django.db import models

# Create your models here.
class provinsi(models.Model):
    nama = models.CharField(max_length=30)
    mati = models.IntegerField(default=0)
    positif = models.IntegerField(default=0)
    sembuh = models.IntegerField(default=0)

stats/views.py
from django.shortcuts import render
from .models import provinsi
from django.views.generic import ListView

# Create your views here.
class showprovinsiView(ListView):
    model = provinsi
    template_name = 'stats/face.html'
    ordering = ['-positif']

stats/templates/stats/face.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
<title>Statistics</title>
<link rel="stylesheet" href="{% static 'stats/stylecard.css' %}"> 
{% endblock meta %}

{% block content %}

<div class="photo-page" style="max-width: 1000px; margin-left:24%; margin-top:5%; margin-bottom:5%">
    {% for prov in object_list %}
    <div class="card card-tall" style="color:black; background-color:rgb(117, 193, 255)">
        <h1 style="border-bottom: 3px solid black; "><a href ="{% url 'detil:detil' prov.id %}" style="color: black">{{ prov.nama }}</a></h1>
        <p style="font-size: 20px;">Meninggal</p>
        <h2>{{ prov.mati }}</h2>
        <p style="font-size: 20px;">Positif</p>
        <h2>{{ prov.positif }}</h2>
        <p style="font-size: 20px;">Sembuh</p>
        <h2>{{ prov.sembuh }}</h2>
    </div>
    {% endfor %}
</div>

{% endblock content %}