berita/urls.py
from django.urls import path
from . import views
from .views import showBeritaViews


app_name = 'berita'

urlpatterns = [
    path('', showBeritaViews.as_view(), name='beritahome'),
]

bintang/urls.py
from django.urls import path
from django.conf.urls import url 

from . import views

app_name = 'bintang'

urlpatterns = [
    path('submisi/', views.submisi, name='submisi'),
    path('detail/<int:detail_id>', views.detail, name='detail'),
    path('delete/<int:delete_id>', views.delete, name='delete'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

projectsaveus/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('stats/', include('stats.urls')),
    path('bintang/', include('bintang.urls')),
    path('detil/', include('detil.urls')),
    path('berita/', include('berita.urls')),
    path('tips/', include('tips.urls')),
]

stats/urls.py
from django.urls import path
from . import views
from .views import showprovinsiView


app_name = 'stats'

urlpatterns = [
    path('', showprovinsiView.as_view(), name='stathome'),
]

tips/urls.py
from django.urls import path
from . import views

app_name = 'tips'

urlpatterns = [
    path('cuci-tangan/', views.cuci_tangan, name='cuci_tangan'),
    path('di-rumah/', views.di_rumah, name='di_rumah'),
    path('di-luar-rumah', views.di_luar_rumah, name='di_luar_rumah'),
    path('', views.add_jurnal, name='add_jurnal'),
    path('view-jurnal/', views.view_jurnal, name='view_jurnal'),
    
    
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700&display=swap" rel="stylesheet">
    <!-- Bootstrap 4 -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

  <!-- Font Awesome -->
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/e76dc76644.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">  
  {% block meta %}
      
    {% endblock meta %}
</head>
<body>
    <header>
        <nav>
            <img src="{% static 'img/us_logo.svg' %}" alt="" class="logo">
            <a href="{% url 'home:index' %}">Beranda</a>
            <a href="{% url 'berita:beritahome' %}">Berita</a>
            <a href="{% url 'stats:stathome' %}">Statistik</a>
            <a href="{% url 'tips:add_jurnal' %}">Tindakan</a>
            <a href="{% url 'bintang:submisi' %}">Submisi</a>
        </nav>
    </header>
    {% block content %}
    
    {% endblock content %}
    <footer>
        <h6>FOLLOW US ON</h6>
        <div class="social">
            <a href="#"><i class="fab fa-twitter"></i> <p>@projectsaveus</p></a>
            <a href="#"><i class="fab fa-instagram"></i> <p>@projectsaveus</p></a>
        </div>
        <div class="copyright"><p>Copyright © 2020 ProjectSaveUs</p></div>
    </footer>
</body>
</html>