home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

projectsaveus/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('stats/', include('stats.urls')),
    path('bintang/', include('bintang.urls')),
    path('detil/', include('detil.urls')),
    path('berita/', include('berita.urls')),
    path('tips/', include('tips.urls')),
]

tips/urls.py
from django.urls import path
from . import views

app_name = 'tips'

urlpatterns = [
    path('cuci-tangan/', views.cuci_tangan, name='cuci_tangan'),
    path('di-rumah/', views.di_rumah, name='di_rumah'),
    path('di-luar-rumah', views.di_luar_rumah, name='di_luar_rumah'),
    path('', views.add_jurnal, name='add_jurnal'),
    path('view-jurnal/', views.view_jurnal, name='view_jurnal'),
    
    
]

tips/models.py
from django.db import models

# Create your models here.
class Checkin(models.Model):
    Subject = models.CharField(max_length=50)
    Date = models.CharField(max_length=50)
    Message = models.CharField(max_length=200)

tips/forms.py
from django import forms
from .models import Checkin

class CheckinForm(forms.ModelForm):
    class Meta:
        model = Checkin
        fields=['Subject','Date','Message']
        widgets={
            'Subject' : forms.TextInput(attrs={'class':'form-control'}),
            'Date' :forms.TextInput(attrs={'class':'form-control'}),
            'Message' :forms.TextInput(attrs={'class':'form-control'}),
        }

tips/views.py
from django.shortcuts import render, redirect
from .models import Checkin
from .forms import CheckinForm

# Create your views here.

def cuci_tangan(request):
    return render(request, 'cuci_tangan.html')

def di_rumah(request):
    return render(request, 'di_rumah.html')

def di_luar_rumah(request):
    return render(request, 'di_luar_rumah.html')

def add_jurnal(request):
    if request.method == 'POST':
        form = CheckinForm(request.POST)
        if form.is_valid():
            jurnal = form.save()
            jurnal.save()
            return redirect('tips:view_jurnal')
    else:
        form = CheckinForm()

    return render(request, 'edukasi.html',{'form':form})

def view_jurnal(request):
    semua_jurnal = Checkin.objects.order_by('Subject')
    return render(request,'view_jurnal.html',{'semua_jurnal':semua_jurnal})

tips/templates/cuci_tangan.html
{% extends 'base.html' %}
% load static %}
{% block meta%}
        <title>Edukasi-Cuci Tangan</title>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <!-- My fonts -->
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet"> 

        <!-- My CSS -->
       

        <link rel="stylesheet" type="text/css" href="style.css">
     

    <style>

        body{
            font: Montserrat;
        }
        .judul{
            color: rgba(0, 0, 0, 0.900);
            font-size: 20px;
            font-weight: 500;
        }
        .videod > * {
            margin-top: 0.5em;
            margin-left: 10px;
            width: 30%;
            display: inline-block;
        }
        
        .textp{
            color:rgba(0, 0, 0, 0.750);
            font-weight: 100;
            font-size: 13px;
        }

        .btn1{
            border-radius: 12px;
            background-color: rgb(218, 78, 78);
            color: black;
            font-size: 12px;
            border:rgb(218, 78, 78);
        }

        .btn1:hover{
            background-color: grey;
            text-decoration: none;
        }

    </style>
  {% endblock meta %}


    {% block content %}
        <section style="padding-top: 5em;">
            <div class="container">
                <h5 class="judul">Tips Mencuci Tangan</h5>
                <p class="textp"> coba simak berbagai video terkait di bawah ini: </p>
                <div class="row">
                    <div class="col-md-6">
                        <iframe width="560" height="315" src="https://www.youtube.com/embed/HChg7g6oPjE" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    </div>
                    <div class="col-md-6">
                        <iframe width="560" height="315" src="https://www.youtube.com/embed/I2QQVr5j85s" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    </div>
                  
                </div>
                <p style="margin-top:1em">Edukasi Anak</p>
                <div class="row">
                    <div class="col-md-6">
                        <iframe width="560" height="315" src="https://www.youtube.com/embed/562zTOhVJSE" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    </div>
                    <div class="col-md-6">
                        <iframe width="560" height="315" src="https://www.youtube.com/embed/HANzVCeN_FE" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    </div>
                </div>

                <div class="row">
                <div class="col-md-6" style="padding-bottom: 3em">
                    <a href="https://covid19.kemkes.go.id/warta-infem/begini-cara-mencuci-tangan-yang-benar/"><button class="btn1" href="https://covid19.kemkes.go.id/warta-infem/begini-cara-mencuci-tangan-yang-benar/" style="margin-top: 3em">Artikel Cuci Tangan</button></a>
                    <a href="{% url 'tips:add_jurnal' %}"><button class="btn1" href="{% url 'tips:add_jurnal' %}" >kembali</button></a>
                </div>  
                </div>
            <!-- </div> -->
        </section>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
      

    {% endblock content %}
   

tips/templates/di_luar_rumah.html
{% extends 'base.html' %}
{% load static %}


        {% block meta %}
        <title>Edukasi-di Luar</title>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <!-- My fonts -->
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet"> 

        <!-- My CSS -->
 

        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
 

    <style>

        body{
            font: Montserrat;
        }
        .judul{
            color: rgba(0, 0, 0, 0.900);
            font-size: 20px;
            font-weight: 500;
        }
        .videod > * {
            margin-top: 0.5em;
            margin-left: 10px;
            width: 30%;
            display: inline-block;
        }
        
        .textp{
            color:rgba(0, 0, 0, 0.750);
            font-weight: 100;
            font-size: 13px;
        }

        .btn1{
            border-radius: 12px;
            background-color: rgb(218, 78, 78);
            color: black;
            font-size: 12px;
            border:rgb(218, 78, 78);
        }

        .btn1:hover{
            background-color: grey;
            text-decoration: none;
        }

    </style>
    {% endblock meta %}



    {% block content %}

        <section style="padding-top: 5em;">
            <div class="container">
                <h5 class="judul">Tips di Luar Rumah</h5>
                <p class="textp"> coba simak berbagai video terkait di bawah ini: </p>
                <p style="margin-top:1em">Transportasi Umum</p>
                <div class="row">
                    <div class="col-md-6">
                        <iframe width="560" height="315" src="https://www.youtube.com/embed/m6aksi4dt90" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    </div>
                    <div class="col-md-6">
                        <iframe width="560" height="315" src="https://www.youtube.com/embed/Nob4YIQp0So" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    </div>
                  
                </div>
                <p style="margin-top:1em">Pusat Belanja atau Tempat Rekreasi</p>
                <div class="row">
                    <div class="col-md-6">
                        <iframe width="560" height="315" src="https://www.youtube.com/embed/CWG18AxHpTA" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    </div>
                    <div class="col-md-6">
                        <iframe width="560" height="315" src="https://www.youtube.com/embed/2poRKvJMt6M" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    </div>
                </div>

                <p style="margin-top:1em">Kampus atau Kantor</p>
                <div class="row">
                    <div class="col-md-6">
                        <iframe width="560" height="315" src="https://www.youtube.com/embed/lOkq2Q7cNJE" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    </div>
                    <div class="col-md-6">
                        <iframe width="560" height="315" src="https://www.youtube.com/embed/nenxKQXolo0" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    </div>
                </div>

                <p style="margin-top:1em">Tempat Makan Umum</p>
                <div class="row">
                    <div class="col-md-6">
                        <iframe width="560" height="315" src="https://www.youtube.com/embed/_QWeLPWn2OY" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    </div>
                    <div class="col-md-6">
                        <iframe width="560" height="315" src="https://www.youtube.com/embed/uWWRGWrW1ac" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                        </div>
                    </div>

                <p style="margin-top:1em">Tips Berkegiatan</p>
                    <div class="row">
                        <div class="col-md-6">
                            <iframe width="560" height="315" src="https://www.youtube.com/embed/ObhMGkz95WE" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                        </div>
                    <div class="col-md-6">
                        <iframe width="560" height="315" src="https://www.youtube.com/embed/Gecnie9BOFw" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                            </div>
                    </div>


                <div class="row">
                <div class="col-md-6" style="padding-bottom: 3em">
                    <a href="https://lifestyle.kompas.com/read/2020/03/29/090408220/melindungi-diri-saat-ke-luar-rumah-untuk-cegah-virus-corona?page=all"><button class="btn1" href="https://covid19.kemkes.go.id/warta-infem/begini-cara-mencuci-tangan-yang-benar/" style="margin-top: 3em">Artikel Tips Berkegiatan di Luar Rumah</button></a>
                    <a href="{% url 'tips:add_jurnal' %}"><button class="btn1" href="{% url 'tips:add_jurnal' %}" >kembali</button></a>
                </div>  
                </div>
            </div>
        </section>
        <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>


    {% endblock content %}

    

tips/templates/di_rumah.html
<!doctype html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
    {% block meta %}

        <title>Edukasi-di Rumah</title>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <!-- My fonts -->
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet"> 

        <!-- My CSS -->
        
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

        

    <style>

        body{
            font: Montserrat;
        }
        .judul{
            color: rgba(0, 0, 0, 0.900);
            font-size: 20px;
            font-weight: 500;
        }
        .videod docs{
            margin-top: 0.5em;
            margin-left: 10px;
            width: 30%;
            display: inline-block;
        }
        
        .textp{
            color:rgba(0, 0, 0, 0.750);
            font-weight: 100;
            font-size: 13px;
        }

        .btn1{
            border-radius: 12px;
            background-color: rgb(218, 78, 78);
            color: black;
            font-size: 12px;
            border:rgb(218, 78, 78);
        }

        .btn1:hover{
            background-color: grey;
            text-decoration: none;
        }

    </style>
    {% endblock meta %}



        {% block content %}
        <section style="padding-top: 5em;">
            <div class="container">
                <h5 class="judul">Tips di Rumah</h5>
                <p class="textp"> coba simak berbagai video terkait di bawah ini: </p>
                <div class="row">
                    <div class="col-md-6">
                        <iframe width="560" height="315" src="https://www.youtube.com/embed/HChg7g6oPjE" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    </div>
                    <div class="col-md-6">
                        <iframe width="560" height="315" src="https://www.youtube.com/embed/I2QQVr5j85s" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    </div>
                  
                </div>
                <p style="margin-top:1em">Edukasi Anak</p>
                <div class="row">
                    <div class="col-md-6">
                        <iframe width="560" height="315" src="https://www.youtube.com/embed/562zTOhVJSE" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    </div>
                    <div class="col-md-6">
                        <iframe width="560" height="315" src="https://www.youtube.com/embed/HANzVCeN_FE" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    </div>
                </div>

                <div class="row">
                <div class="col-md-6" style="padding-bottom: 3em">
                    <a href="https://covid19.kemkes.go.id/warta-infem/begini-cara-mencuci-tangan-yang-benar/"><button class="btn1" href="https://covid19.kemkes.go.id/warta-infem/begini-cara-mencuci-tangan-yang-benar/" style="margin-top: 3em">Artikel Tips Berkegiatan di Rumah</button></a>
                    <a href="{% url 'tips:add_jurnal' %}"><button class="btn1" href="{% url 'tips:add_jurnal' %}" >kembali</button></a>
                </div>  
                </div>
            </div>
        </section>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
      
    

    {% endblock content %}
   

tips/templates/edukasi.html
{% extends 'base.html' %}
{% load static %}

 
        <!-- My CSS -->
        {% block meta%}
        <title>Edukasi Covid</title>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <!-- My fonts -->
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet"> 

        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        

        <style>

        body{
            font-family: Montserrat;
        }
        
        .judul{
            color: rgba(0, 0, 0, 0.900);
            font-size: 20px;
            font-weight: 500;
        }

        .judul::after{
            content: "";
            display: block;
            color: black;
        }

        .fotoed1:hover{
            transform: scale(1.1); 
        }

        .fotoed2:hover{
            transform: scale(1.1); 
        }

        .fotoed3:hover{
            transform: scale(1.1); 
        }

        img{
            width: 30%;
        }

        .underpict{
            margin-top: 1em;
            color:rgba(0, 0, 0, 0.750);
            font-size: 15px;
            font-weight:450;
        }

        .undertext{
            color:rgb(87, 85, 85);
            font-size: 12px;
            font-weight: 150;
        }

        .underlink{
            color:black;
        }

        .underlink:hover{
            color: rgb(134, 134, 134);
            font-weight: 50;
            text-decoration: none;
        }
        .textlink{
            color:black;
        }

        .textlink:hover{
            color: rgb(134, 134, 134);
            font-weight: 500;
            text-decoration: none;
        }

        .btn1{
            border-radius: 12px;
            background-color: rgb(218, 78, 78);
            color: black;
            font-size: 12px;
            border:rgb(218, 78, 78);
        }

        .btn1:hover{
            background-color: grey;
            text-decoration: none;
        }
        </style>
    
    {% endblock meta %} 

    
    {% block content %}
        <section style="padding-top: 5em;">
            <div class="container">
                <h5 class="judul">Edukasi Covid-19</h5>
                <div class="row">
                    <div class="col-md-12">
                        <div class="fotoed" style="margin-top: 0.5em;">
                            <img class="fotoed1" src="{% static 'cucitngan2.png'  %}" alt="cuci tangan" href="{% url 'tips:cuci_tangan' %}">
                            <img class="fotoed2" style="margin-left: 50px;" src="{% static 'dirumahbersih.png' %}" alt="dirumah">
                            <img class="fotoed3" style="margin-left: 50px" src="{% static 'diluar.png'  %}" alt="dirumah">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="underpict">
                            <p><a class="textlink" href="{% url 'tips:cuci_tangan' %}"><span>Tips Mencuci Tangan</span></a><a class="textlink" href="{% url 'tips:di_rumah' %}"><span style="margin-left:235px">Tips di Rumah</span></a>
                                <a class="textlink" href="{% url 'tips:di_luar_rumah' %}"><span style="margin-left:265px">Tips di Luar Rumah</span></a>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="undertext">
                            <p><a class="underlink" href="{% url 'tips:cuci_tangan' %}"><span>Lihat selengkapnya</span></a><a class="underlink" href="{% url 'tips:di_rumah' %}"><span style="margin-left:280px">Lihat selengkapnya</span></a>
                                <a class="underlink" href="{% url 'tips:di_luar_rumah' %}"><span style="margin-left:260px">Lihat selengkapnya</span></a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section style="margin-top:5em">
            <div class="container">
                <h5 class="judul">Check-in Harian</h5>
                <div class="row">
                    <div class="col-md-12">
                   
                            <form method="POST">
                                {% csrf_token %}
                                <div class="mr-auto ml-auto" style="width: 50%; ">
                                    {% for field in form %}
                                    <div class="form-group">
                                        {{ field.label_tag }}
                                        {{ field }}
                                    </div>
                                    {% endfor %}
                                </div>
                                <center>
                                <div class="container">
                                    <input type="submit" value="tambah ke jurnal" class="btn btn-primary click" style="border-radius: 12px;">
                                    <div>
                                        <a href="{% url 'tips:view_jurnal' %}"><button class="btn btn-primary click" type="button" style="margin-top:1em;margin-bottom: 2em;">View Jurnal</button></a>
                                    </div>
                                </div>
                            </center>
                            </form>
                       
                    </div>
                </div>
            </div>
            
        </section>
         <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  
    {% endblock content %}
    

   

tips/templates/view_jurnal.html
{% extends 'base.html' %}
{% load static %}

{% block meta%}
    <title>view jurnal</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- My fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet"> 

    <!-- My CSS -->

    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">


    <style>
        body {
            font-family:'Montserrat', sans-serif !important;
            font-size: 15px;
            font-weight: bold;
            margin: 0 30px;
        }

        .btn1{
            border-radius: 12px;
            background-color: rgb(218, 78, 78);
            color: black;
            font-size: 12px;
            border:rgb(218, 78, 78);
        }

        .judul{
            color: rgba(0, 0, 0, 0.900);
            font-size: 20px;
            font-weight: 500;
        }
    </style>
    <!-- akhir style -->
    {% endblock meta %}
    
   <!-- view matkul -->
   {% block content %}
   <h5 class="judul" style="padding-top: 2em">View Jurnal</h5>
    <div style="margin-top:1em">
     <table class="table table-striped ">
         <thead>
             <tr>
                 <th scope="col">Subject</th>
                 <th scope="col">Tanggal</th>
                 <th scope="col">Pesan Jurnal</th>
                 
             </tr>
         </thead>
         <tbody>
             {% for i in semua_jurnal %}
             <tr>
                 <td>
                     <a>{{ i.Subject }}</a>
                 </td>
                 <td>{{ i.Date}}</td>
                 <td>{{ i.Message}}</td>
                 
            
             </tr>
             {% endfor %}
         </tbody>
     </table>   
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    {% endblock content %}

    
  